services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
    depends_on:
      - redis
      - postgres

  generate-image:
    build:
      context: .
      dockerfile: apps/generate_image/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - IPFS_PROJECT_ID=${IPFS_PROJECT_ID}
      - IPFS_PROJECT_SECRET=${IPFS_PROJECT_SECRET}
      - BROWSERLESS_WSS=${BROWSERLESS_WSS}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN}
    depends_on:
      - redis
      - postgres

  mint:
    build:
      context: .
      dockerfile: apps/mint/Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - PRIVATE_KEY=${PRIVATE_KEY}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
