services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      platforms:
        - "linux/amd64"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-nicepfp}
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST:-http://localhost:3000}
      - IPFS_PROJECT_ID=${IPFS_PROJECT_ID}
      - IPFS_PROJECT_SECRET=${IPFS_PROJECT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - nicepfp-network

  generate-image:
    build:
      context: .
      dockerfile: apps/generate_image/Dockerfile
      platforms:
        - "linux/amd64"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-nicepfp}
      - REDIS_URL=redis://redis:6379
      - PRIVATE_KEY=${PRIVATE_KEY}
      - IPFS_PROJECT_ID=${IPFS_PROJECT_ID}
      - IPFS_PROJECT_SECRET=${IPFS_PROJECT_SECRET}
      - BROWSERLESS_URL=${BROWSERLESS_URL}
      - BROWSERLESS_TOKEN=${BROWSERLESS_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - nicepfp-network

  mint:
    build:
      context: .
      dockerfile: apps/mint/Dockerfile
      platforms:
        - "linux/amd64"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-nicepfp}
      - REDIS_URL=redis://redis:6379
      - PRIVATE_KEY=${PRIVATE_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - nicepfp-network

  migrate:
    build:
      context: .
      dockerfile: prisma/migrate.Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-nicepfp}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nicepfp-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - nicepfp-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-nicepfp}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nicepfp-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-nicepfp}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nicepfp-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
