packages:
  - apps/*
  - packages/*

# Required for pnpm deploy to work with workspace dependencies
injectWorkspacePackages: true

onlyBuiltDependencies:
  - esbuild
  - keccak
  - puppeteer
  - react-p5
  - secp256k1
  - sharp
