import {
  Box,
  Stat,
  StatLabel,
  StatHelpText,
  Divider,
  useColorModeValue,
  Link,
} from "@chakra-ui/react";
import { ExternalLinkIcon } from "@chakra-ui/icons";

export default function Card1() {
  return (
    <Box
      w="100%"
      h="56"
      boxShadow="base"
      p={3}
      rounded="md"
      bg={useColorModeValue("white", "gray.700")}
    >
      <Stat>
        <StatLabel m={2} fontFamily="Spartan" fontWeight="bold">
          How is it generated?
        </StatLabel>
        <Divider />
        <StatHelpText m={3} fontFamily="Spartan">
          The doodles are generated by a recurrent neural network model trained
          on millions of doodles collected from the{" "}
          <Link href="https://quickdraw.withgoogle.com/" isExternal>
            Quick, Draw! game <ExternalLinkIcon mx="2px" />
          </Link>
          .
        </StatHelpText>
      </Stat>
    </Box>
  );
}
